# Generated by Django 2.0.13 on 2019-11-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimierung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='solver',
        ),
    ]
