# Generated by Django 2.0.13 on 2019-07-04 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klassenstundenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lehreinheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Klassenstundenplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Klassenstundenplan')),
            ],
        ),
        migrations.CreateModel(
            name='Lehrer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Kurzname', models.CharField(max_length=10)),
                ('Stundenzahl', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LehrerBelegt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Lehrer')),
            ],
        ),
        migrations.CreateModel(
            name='Lehrerstundenplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Lehrer')),
            ],
        ),
        migrations.CreateModel(
            name='Lehrfaecher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wochenstunden', models.IntegerField()),
                ('tandemstunden', models.IntegerField(default=0)),
                ('klassengruppen', models.IntegerField(default=1)),
                ('verpflichtend', models.CharField(choices=[('muss', 'Muss getrennt werden'), ('kann', 'Kann getrennt werden')], default='kann', max_length=10)),
                ('blockstunden', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Nutzbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Lehrer')),
            ],
        ),
        migrations.CreateModel(
            name='Raum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Beschreibung', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaumBelegt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Raum')),
            ],
        ),
        migrations.CreateModel(
            name='Schulfach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Parallel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulfach')),
            ],
        ),
        migrations.CreateModel(
            name='Schulklasse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Faecher', models.ManyToManyField(through='datainput.Lehrfaecher', to='datainput.Schulfach')),
                ('HauptTandem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TandemKlassen', to='datainput.Lehrer')),
                ('Klassenlehrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='HauptKlasse', to='datainput.Lehrer')),
                ('PartnerLehrer', models.ManyToManyField(through='datainput.Partner', to='datainput.Lehrer')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=20)),
                ('Zeit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Uebergreifung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulfach')),
                ('schulklasse', models.ManyToManyField(to='datainput.Schulklasse')),
            ],
        ),
        migrations.CreateModel(
            name='Unterrricht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulfach')),
                ('lehrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Lehrer')),
            ],
        ),
        migrations.CreateModel(
            name='VorgabeEinheit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulfach')),
                ('Lehrperson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datainput.Lehrer')),
                ('Schulklasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulklasse')),
                ('Zeitslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Slot')),
            ],
        ),
        migrations.AddField(
            model_name='raumbelegt',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Slot'),
        ),
        migrations.AddField(
            model_name='raum',
            name='Nichtfrei',
            field=models.ManyToManyField(through='datainput.RaumBelegt', to='datainput.Slot'),
        ),
        migrations.AddField(
            model_name='raum',
            name='faecher',
            field=models.ManyToManyField(through='datainput.Nutzbar', to='datainput.Schulfach'),
        ),
        migrations.AddField(
            model_name='partner',
            name='schulklasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulklasse'),
        ),
        migrations.AddField(
            model_name='nutzbar',
            name='raum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Raum'),
        ),
        migrations.AddField(
            model_name='nutzbar',
            name='schulfach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulfach'),
        ),
        migrations.AddField(
            model_name='lehrfaecher',
            name='schulfach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulfach'),
        ),
        migrations.AddField(
            model_name='lehrfaecher',
            name='schulklasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulklasse'),
        ),
        migrations.AddField(
            model_name='lehrerbelegt',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Slot'),
        ),
        migrations.AddField(
            model_name='lehrer',
            name='Faecher',
            field=models.ManyToManyField(through='datainput.Unterrricht', to='datainput.Schulfach'),
        ),
        migrations.AddField(
            model_name='lehrer',
            name='NichtDa',
            field=models.ManyToManyField(through='datainput.LehrerBelegt', to='datainput.Slot'),
        ),
        migrations.AddField(
            model_name='lehreinheit',
            name='Lehrerstundenplan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Lehrerstundenplan'),
        ),
        migrations.AddField(
            model_name='lehreinheit',
            name='Schulfach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulfach'),
        ),
        migrations.AddField(
            model_name='lehreinheit',
            name='Zeitslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Slot'),
        ),
        migrations.AddField(
            model_name='klassenstundenplan',
            name='Schulklasse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulklasse'),
        ),
    ]
