# Generated by Django 2.0.13 on 2019-07-04 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StundenzahlproTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stundenzahl', models.IntegerField()),
                ('schulklasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Schulklasse')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='slot',
            name='Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Tag'),
        ),
        migrations.AddField(
            model_name='stundenzahlprotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datainput.Tag'),
        ),
        migrations.AddField(
            model_name='schulklasse',
            name='Stundenzahlen',
            field=models.ManyToManyField(through='datainput.StundenzahlproTag', to='datainput.Tag'),
        ),
    ]
