# Generated by Django 2.0.13 on 2019-07-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0002_auto_20190704_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stunde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stunde', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='slot',
            name='Zeit',
        ),
        migrations.AddField(
            model_name='slot',
            name='Stunde',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='datainput.Stunde'),
            preserve_default=False,
        ),
    ]
