# Generated by Django 2.0.13 on 2019-07-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0003_auto_20190704_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stundenzahlprotag',
            old_name='stundenzahl',
            new_name='Stundenzahl',
        ),
    ]
