# Generated by Django 2.0.13 on 2019-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0004_auto_20190709_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='stunde',
            name='Index',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tag',
            name='Index',
            field=models.IntegerField(default=1),
        ),
    ]
