# Generated by Django 2.0.13 on 2019-07-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0005_auto_20190709_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stunde',
            name='Index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Index',
            field=models.IntegerField(),
        ),
    ]
