# Generated by Django 2.0.13 on 2019-07-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0006_auto_20190709_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='lehrer',
            name='Tandem',
            field=models.CharField(choices=[(1, 'Ja'), (0, 'Nein')], default=1, max_length=10),
        ),
    ]
