# Generated by Django 2.0.13 on 2019-07-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0011_auto_20190711_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimierungsergebnis',
            name='Index',
            field=models.IntegerField(default=0),
        ),
    ]
