# Generated by Django 2.0.13 on 2019-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0012_optimierungsergebnis_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimierungsergebnis',
            name='Index',
            field=models.IntegerField(),
        ),
    ]
