# Generated by Django 2.0.13 on 2019-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0013_auto_20190715_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehrfaecher',
            name='blockstunden',
            field=models.IntegerField(default=0),
        ),
    ]
