# Generated by Django 2.0.13 on 2019-07-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0014_auto_20190718_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lehrer',
            name='Tandem',
        ),
    ]
