# Generated by Django 2.0.13 on 2019-07-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0015_remove_lehrer_tandem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lehrfaecher',
            name='blockstunden',
            field=models.IntegerField(default=1),
        ),
    ]
