# Generated by Django 2.0.13 on 2019-07-24 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datainput', '0016_auto_20190722_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='klassenstundenplan',
            name='Schulklasse',
        ),
        migrations.RemoveField(
            model_name='lehrerstundenplan',
            name='Lehrer',
        ),
        migrations.DeleteModel(
            name='Klassenstundenplan',
        ),
        migrations.DeleteModel(
            name='Lehrerstundenplan',
        ),
    ]
